name: Autopep8

on: [pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade autopep8
        pip install autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Parsing the code with autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive $(git ls-files '*.py')
    - name: Commit autopep8 fixes
      run: |
        git config --global user.name "Workflow Bot"
        git config --global user.email "paryz.filip+workflow.bot@gmail.com"
        git add .
        git commit -m "Autopep8 formatting"
        git push