name: Autopep8 and Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install autopep8 dependencies
      run: |
        python -m pip install --upgrade autopep8
        pip install autopep8
    - name: Install pylint dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Parsing the code with autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive $(git ls-files '*.py')
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Commit autopep8 fixes
      run: |
        git config --global user.name "Workflow Bot"
        git config --global user.email "paryz.filip+workflow.bot@gmail.com"
        git add .
        git commit -m "Autopep8 formatting"

